import Head from "next/head";

export default function Header() {
  return (
    <Head>
      <title>Folieum</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}



