import Head from "next/head";
import { useSession } from "next-auth/react";
import Link from "next/link";
import Signout from "~/components/auth/signout";
import Signin from "~/components/auth/signin";
import styles from "~/components/header/styles.module.css";
import { BiSolidUserCircle } from 'react-icons/bi';
import { useState } from "react";

export default function Header() {
  const { status } = useSession();

  const [isOpen, setIsOpen] = useState(false)

  const toggleMenu = () => {
    setIsOpen(!isOpen)
  }

  return (
    <div>
      <Head>
        <title>Folieum</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.header}>
          <div className={styles.header_menu}>
            <div className={styles.header_menu_icon} onClick={toggleMenu}>
              <BiSolidUserCircle className={styles.header_menu_icon}/>
            </div>
            <ul className={`${styles.header_links} ${isOpen ? styles.header_links_open : ""}`}>
              {status === "authenticated" && 
                <li>
                  <Link className={styles.header_link} href="/profile">
                    <BiSolidUserCircle className={styles.header_links_icon}/>
                    <label className={styles.header_text}>Profile</label>
                  </Link>
                </li>
              }
              <li>
                {status === "authenticated" ? 
                  <Signout /> : <Signin />
                } 
              </li>
            </ul>
          </div>
      </nav>
    </div>
  );
}
